### ISSUE TITLE
Moods are broken.

### ISSUE THREAD

**Issue by MrPowerGamerBR** [Delthas/JavaSkype#10]
When you try to get a user's mood, it returns ```null``` instead of the users mood.

**Comment by MrPowerGamerBR** [comment]
Also, I'm not using the latest commit (I'm using a build from this commit: https://github.com/Delthas/JavaSkype/commit/a37d5afebbdc3b54f7b4573548197eff0bab9e08 ) because the latest one is giving errors, so maybe this bug isn't happening on newer version.

**Comment by Delthas** [comment]
That's normal actually. Sometimes the user's mood is not visible so Skype doesn't send it. For example if you try getting the mood of a user you're not friends with, it will probably not be visible.

As per the Javadoc for the function:
> The mood (status) of this user, or null if not visible.

There may actually be a way to get the user mood even though you're not friends though, and I'll try to implement that soon.

**Comment by MrPowerGamerBR** [comment]
But all of my contacts are returning null instead of the mood. (And yes,
I'm friends with them)

Just a FYI to help you a bit (or not), every Skype API for Java has broken
moods except Skype4J.

Em 2 de ago de 2016 09:25, "Delthas" <notifications@github.com> escreveu:

**Comment by Delthas** [comment]
(The issue closed itself apprently because of the "fixes #10" part of the commit message.)

I added new endpoints to fetch the moods. I think most friends moods should be non-null now. Could you please download the lastest version (1.0.9) and tell me if that's the case? Thanks.

**Comment by Delthas** [comment]
I'm not sure I can do any better. Sometimes Skype can't fetch friends' moods either, when you haven't seen them online in a long time.
Still, normally there should be as many non-null moods as when you try with Skype4J.
If that's the case, you can close the issue.

**Comment by MrPowerGamerBR** [comment]
@Delthas same issue in Skype4J, so I will close this issue because this is a Skype API issue, not a JavaSkype issue.

Anyway, thanks for fixing moods (and indirectly fixing my other issue :tongue: ), at least now there is two Skype APIs for Java where moods are working. (the rest of the APIs have broken moods)
