### ISSUE TITLE
Adding the API into a java project

### ISSUE THREAD

**Issue by tayabsoomro** [Delthas/JavaSkype#17]
I am having trouble adding this API into my java project, do you have a detailed tutorial on how to add this API into a new java project? I am using eclipse by the way.

**Comment by Delthas** [comment]
I suppose you aren't using Maven, in which case the easiest way to use this library would be to directly download the JAR file of the library, at the link https://repo1.maven.org/maven2/fr/delthas/javaskype/<version>/javaskype-<version>.jar, e.g. https://repo1.maven.org/maven2/fr/delthas/javaskype/1.0.18/javaskype-1.0.18.jar (use the latest version).  

The truth is most projects these days use a tool that manages the dependencies of their project. This is called a dependency management tool. There are also tools that can automatically build a project, and they're called build tools. In Java, there's a tool that does both of that and is very used, called Maven. Most projects are "distributed" as Maven dependencies, which means you can very simply add them to your project if your project uses Maven by simply adding a few lines in a project-specific Maven configuration that's called pom.xml.  

In your case, if you really want to get involved in real-world Java programming, I suggest you learn a few tutorials about Maven to understand how to use it. There is a very good book (online, free) online that you could read: http://books.sonatype.com/mvnref-book/reference/ that will let you understand what Maven is very quickly. Once you're done with that, maybe you'll need to browse stackoverflow for specific questions such as "how do I create a runnable jar file with maven?" and you'll be able to add my project as a Maven dependency of yours.
