### ISSUE TITLE
Get self Avatar

### ISSUE THREAD

**Issue by zSteve007** [Delthas/JavaSkype#29]
Code:
`User skypeUser = skype.getSelf();`
`String url = skypeUser.getAvatarUrl();`
`System.out.println("Url = " + url);`

Out: 
`Url = null`

**Comment by Delthas** [comment]
Hello! Sorry for the long wait. I think I have fixes the issue in the latest version, 1.0.20. Could you check and tell me if it works/reopen the issue if it doesn't?

Thanks.
