### ISSUE TITLE
Can I create buttons using this API?

### ISSUE THREAD

**Issue by Desperate10** [Delthas/JavaSkype#33]
Cannot find how to create callback buttons

**Comment by Delthas** [comment]
I don't understand. What do you mean?

**Comment by Desperate10** [comment]
![Example](https://camo.githubusercontent.com/0ed8f1efdebf1ae38c04f59634fca027101cfa15/68747470733a2f2f646f63732e626f746672616d65776f726b2e636f6d2f656e2d75732f696d616765732f736b7970652f736b7970652d626f742d6865726f2d636172642e706e67)
Format: ![Alt Text](url)

**Comment by ItsGravix** [comment]
I was wondering the same thing too...

**Comment by Delthas** [comment]
No, you can simply create button bots using the officiel Skype bot library: https://dev.skype.com/bots
Maybe someone could write Java wrappers for it but it is not a goal of this project.
