### ISSUE TITLE
Error while parsing entity 28

### ISSUE THREAD

**Issue by estuardolh** [delthas/JavaSkype#37]
Hello,

I installed JavaSkype 1.0.22 using Maven on Eclipse.
Running a basic example(one its worked in a previous version and same skype user) i am getting this out:

`Exception in thread "Skype-Receiver-Thread" java.lang.IllegalArgumentException
	at fr.delthas.skype.NotifConnector.parseEntity(NotifConnector.java:792)
	at fr.delthas.skype.NotifConnector.updateThread(NotifConnector.java:738)
	at fr.delthas.skype.NotifConnector.processPacket(NotifConnector.java:254)
	at fr.delthas.skype.NotifConnector.lambda$new$0(NotifConnector.java:73)
	at java.lang.Thread.run(Unknown Source)
`

Enabling debug i see in the log file this at the last two lines:
`nov 22, 2017 10:49:52 PM fr.delthas.skype.NotifConnector parseEntity
ADVERTENCIA: Error while parsing entity 28:0d5d6cff-595d-49d7-9cf8-973173f5233b: unknown network:28
`

Thank you in advance

**Comment by Delthas** [comment]
Hello, thanks for the bug report.
I will look into this this week.

**Comment by estuardolh** [comment]
Maybe Skype translator bot?

**Comment by delthas** [comment]
I have just pushed 1.0.23 which addresses this issue. Could you try it and tell me if it works?

Thanks.

**Comment by estuardolh** [comment]
Okay. I have no message error about above. 
Thank you!

**Comment by delthas** [comment]
Great to hear!
